### ISSUE TITLE
update to build in Xcode 14?

### ISSUE THREAD

**Issue by schriftgestalt** [murasu/Hibizcus#12]
The version from the app store is crashing so I tried to build it myself but the BinarySwift framework is compiled for the wrong python version.

**Comment by murasu** [comment]
BinarySwift has no dependancy on Python.

I have a TestFlight version that does not crash. Will try pushing it to release in a couple of days.

**Comment by schriftgestalt** [comment]
I meant Swift not python.

**Comment by murasu** [comment]
Okay, thank you. I'll take a look.

**Comment by murasu** [comment]
@schriftgestalt Which macOS version is the app from the AppStore crashing in? I just downloaded it in 12.6 and it runs ok. Also, if you like, I can invite you to TestFlight so you can run the latest build while I check building it in Xcode 14.

**Comment by murasu** [comment]
Fixed!  Updated the BinarySwift framework!

**Comment by schriftgestalt** [comment]
Thanks.
