### ISSUE TITLE
Regular expression search in Words panel

### ISSUE THREAD

**Issue by sovichet** [murasu/Hibizcus#4]
It may not be very important but it could be helpful in some cases, I think. Like in Khmer, we might want to search for words that contain 2 sub-consonant and a `ro-khmer.pre`.

**Comment by murasu** [comment]
Thanks, @sovichet. Good feedback. The regex search feature has been included in the latest release. You may download it from the AppStore. I've also updated the sources.
<img width="908" alt="Notification_Center" src="https://user-images.githubusercontent.com/22926756/132359521-81d4592b-e69d-436b-b139-35681d866253.png">
