### ISSUE TITLE
Build Khmer cluster data

### ISSUE THREAD

**Issue by sovichet** [murasu/Hibizcus#7]
Todos:

- [x] Map letters into the syllable syntax (Unicode? OpenType? or another?) / I'll help exploring this.
- [x] Consider double sub-consonant case -> created Consonants with 1 Coeng, and Consonant with 2 Coengs
- [x] Added composite vowels
- [x] Remove "Independent Vowels" section

**Comment by murasu** [comment]
@sovichet with the latest version, can we take all the above as done?
